Repository wecode-bootcamp-korea/45-1st-Agile-frontend, pull requests merged in 2023-05, with the labels that each got.

#5 [45기 박현아] ADD : payment 페이지 레이아웃
  src/pages/Payment/Payment.js
  src/pages/Payment/Payment.scss
  src/pages/Payment/components/Agreement.js
  src/pages/Payment/components/Agreement.scss
  src/pages/Payment/components/OrderList.js
  src/pages/Payment/components/OrderList.scss
  src/pages/Payment/components/Orderer.js
  src/pages/Payment/components/Orderer.scss
  src/pages/Payment/components/PaymentInfo.js
  src/pages/Payment/components/PaymentInfo.scss
  src/pages/Payment/components/PaymentMethod.js
  src/pages/Payment/components/PaymentMethod.scss
  src/pages/Payment/components/Shipment.js
  src/pages/Payment/components/Shipment.scss
  src/pages/Payment/components/ShipmentSelect.js
  src/pages/Payment/components/ShipmentSelect.scss
  src/pages/Payment/components/Subscribe.js
  src/pages/Payment/components/Subscribe.scss
Labels: 완료

#12 [45기 이소진] Add : 로그인 레이아웃 구현
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/styles/reset.scss
Labels: 완료

#4 [45기 김희연] Add: 상품디테일 페이지 레이아웃 구성
  public/data/data2.json
  public/images/details/book-sample.png
  public/images/details/heart.svg
  public/images/details/share.svg
  src/pages/Details/Details.js
  src/pages/Details/Details.scss
  src/pages/Details/components/Button.js
  src/pages/Details/components/Button.scss
  src/pages/Details/components/Contents.js
  src/pages/Details/components/Contents.scss
  src/pages/Details/components/DescriptionArea.js
  src/pages/Details/components/DescriptionArea.scss
  src/pages/Details/components/QuantityBox.js
  src/pages/Details/components/QuantityBox.scss
  src/pages/Details/components/Review.js
  src/pages/Details/components/Review.scss
  src/pages/Details/components/ReviewList.js
  src/pages/Details/components/ReviewList.scss
  src/pages/Details/components/ShareButton.js
  src/pages/Details/components/ShareButton.scss
  src/pages/Details/components/ShippingInfo.js
  src/pages/Details/components/ShippingInfo.scss
  src/pages/Details/components/SubscribeOptions.js
  src/pages/Details/components/SubscribeOptions.scss
  src/pages/Details/components/WishlistButton.js
  src/pages/Details/components/WishlistButton.scss
Labels: 멘토 리뷰 요청

#8 [45기 이소진] Add : 회원가입 레이아웃 구현
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
Labels: 멘토 리뷰 요청

#10 [45기 박현아] Add: 마이페이지 레이아웃 구현
  public/data/subscribeData.json
  public/images/mypage/brunch.jpg
  src/Router.js
  src/pages/Mypage/Mypage.js
  src/pages/Mypage/Mypage.scss
  src/pages/Mypage/components/ItemTitle.js
  src/pages/Mypage/components/ItemTitle.scss
  src/pages/Mypage/components/Likes.js
  src/pages/Mypage/components/Likes.scss
  src/pages/Mypage/components/LikesProduct.js
  src/pages/Mypage/components/LikesProduct.scss
  src/pages/Mypage/components/MenuBar.js
  src/pages/Mypage/components/MenuBar.scss
  src/pages/Mypage/components/MypageTop.js
  src/pages/Mypage/components/MypageTop.scss
  src/pages/Mypage/components/OrderDelivery.js
  src/pages/Mypage/components/OrderDelivery.scss
  src/pages/Mypage/components/Subscribes.js
  src/pages/Mypage/components/Subscribes.scss
  src/pages/Mypage/components/SubscribesProduct.js
  src/pages/Mypage/components/SubscribesProduct.scss
  src/pages/Mypage/components/UserInfoUpdate.js
  src/pages/Mypage/components/UserInfoUpdate.scss
Labels: 멘토 리뷰 요청

#7 [45기 오승민] Add : 장바구니페이지 레이아웃 구현
  public/data/data.json
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/Components/BuyingButton.js
  src/pages/Cart/Components/BuyingButton.scss
  src/pages/Cart/Components/Count.js
  src/pages/Cart/Components/Count.scss
  src/pages/Cart/Components/List.js
  src/pages/Cart/Components/List.scss
  src/pages/Cart/Components/ListItem.js
  src/pages/Cart/Components/ListItem.scss
  src/pages/Cart/Components/OrderInfo.js
  src/pages/Cart/Components/OrderInfo.scss
  src/pages/Cart/Components/Product.js
  src/pages/Cart/Components/Product.scss
  src/pages/Cart/Components/Summary.js
  src/pages/Cart/Components/Summary.scss
  src/pages/Cart/Components/Title.js
  src/pages/Cart/Components/Title.scss
Labels: 완료

#11 [45기 이소진] Add : 로그인 기능 구현
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/styles/reset.scss
Labels: 완료

#19 [45기 김희연] Add: Footer 구현
  public/images/details/null.png
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Footer/FooterButton.js
  src/components/Footer/FooterButton.scss
  src/pages/Details/Mainlayout.js
Labels: 멘토 리뷰 요청

#9 [45기 김희연] Add: 상품디테일 페이지 param ID 확인, fetch로 Mock데이터 호출 기능 구현
  public/data/cartdata.json
  public/data/data2.json
  public/data/reviewsdata.json
  public/images/details/411888208(2).jpg
  public/images/details/ico_product_soldout.gif
  public/images/details/red-heart.svg
  src/ config.js
  src/Router.js
  src/pages/Details/Details.js
  src/pages/Details/Details.scss
  src/pages/Details/components/Button.js
  src/pages/Details/components/CartModal.js
  src/pages/Details/components/CartModal.scss
  src/pages/Details/components/CartRecheckModal.js
  src/pages/Details/components/CartRecheckModal.scss
  src/pages/Details/components/Contents.js
  src/pages/Details/components/Contents.scss
  src/pages/Details/components/DescriptionArea.js
  src/pages/Details/components/DescriptionArea.scss
  src/pages/Details/components/ProductInformation.js
  src/pages/Details/components/ProductInformation.scss
  src/pages/Details/components/QuantityBox.js
  src/pages/Details/components/Review.js
  src/pages/Details/components/Review.scss
  src/pages/Details/components/ReviewList.js
  src/pages/Details/components/ReviewList.scss
  src/pages/Details/components/ReviewPaginationButton.js
  src/pages/Details/components/ReviewPaginationButton.scss
  src/pages/Details/components/ShippingInfo.js
  src/pages/Details/components/ShippingInfo.scss
  src/pages/Details/components/WishlistButton.js
  src/pages/Login/Login.js
  src/pages/Payment/Payment.js
Labels: 멘토 리뷰 요청

#21 [45기 김희연] config import 파일명 수정본
  src/pages/Details/Details.js
Labels: 도움 요청, 멘토 리뷰 요청

#17 [45기 이소진] Add : 회원가입 기능 구현
  src/pages/Login/Login.js
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
Labels: 멘토 리뷰 요청

#18 [45기 박현아] Add: 마이페이지 기능구현
  public/data/userData_mypage.json
  src/pages/Mypage/Mypage.js
  src/pages/Mypage/Mypage.scss
  src/pages/Mypage/components/ConfirmPassword.js
  src/pages/Mypage/components/ConfirmPassword.scss
  src/pages/Mypage/components/ItemTitle.js
  src/pages/Mypage/components/ItemTitle.scss
  src/pages/Mypage/components/Likes.js
  src/pages/Mypage/components/Likes.scss
  src/pages/Mypage/components/LikesList.js
  src/pages/Mypage/components/LikesList.scss
  src/pages/Mypage/components/LikesProduct.js
  src/pages/Mypage/components/LikesProduct.scss
  src/pages/Mypage/components/MypageTop.js
  src/pages/Mypage/components/Subscribes.js
  src/pages/Mypage/components/Subscribes.scss
  src/pages/Mypage/components/SubscribesProduct.js
  src/pages/Mypage/components/SubscribesProduct.scss
  src/pages/Mypage/components/UserInfoUpdate.js
  src/pages/Mypage/components/UserInfoUpdate.scss
Labels: 멘토 리뷰 요청

#25 [45기 김희연] 상세페이지 추가 기능 구현
  src/pages/Details/Details.js
  src/pages/Details/Mainlayout.js
  src/pages/Details/components/Contents.js
  src/pages/Details/components/SubscribeOptions.js
  src/pages/Details/components/WishlistButton.js
  src/pages/Payment/Payment.js
Labels: 멘토 리뷰 요청

#26 [45기 이소진] Add : 로그인 기능 구현
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
Labels: 멘토 리뷰 요청

#22 [45기 박현아] Add: 마이페이지 통신구현
  public/data/subscribeData.json
  src/pages/Mypage/Mypage.js
  src/pages/Mypage/components/ConfirmPassword.js
  src/pages/Mypage/components/Likes.js
  src/pages/Mypage/components/LikesList.js
  src/pages/Mypage/components/LikesList.scss
  src/pages/Mypage/components/LikesProduct.js
  src/pages/Mypage/components/MenuBar.js
  src/pages/Mypage/components/MypageTop.js
  src/pages/Mypage/components/MypageTop.scss
  src/pages/Mypage/components/OrderDelivery.js
  src/pages/Mypage/components/OrderItems.js
  src/pages/Mypage/components/OrderItems.scss
  src/pages/Mypage/components/OrderProducts.js
  src/pages/Mypage/components/OrderProducts.scss
  src/pages/Mypage/components/OrderStatus.js
  src/pages/Mypage/components/OrderStatus.scss
  src/pages/Mypage/components/Subscribes.js
  src/pages/Mypage/components/SubscribesProduct.js
  src/pages/Mypage/components/UserInfoUpdate.js
  src/pages/Mypage/components/UserInfoUpdate.scss
Labels: 멘토 리뷰 요청

#28 [45기 이소진] Add : 아이디, 회원가입 페이지 로고 추가
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
Labels: 멘토 리뷰 요청

#27 [45기 김준섭] Add : 메인페이지 및 상품리스트 사진 url추가 및 자잘한 버그 수정
  public/images/productlist/productlist-11.mp4
  public/images/productlist/productlist-1null.mp4
  public/images/productlist/productlist-22.mp4
  public/images/productlist/productlist-23.mp4
  public/images/productlist/productlist-2null.mp4
  public/images/productlist/productlist-34.mp4
  public/images/productlist/productlist-35.mp4
  public/images/productlist/productlist-3null.mp4
  public/images/productlist/productlist-46.mp4
  public/images/productlist/productlist-47.mp4
  public/images/productlist/productlist-4null.mp4
  src/components/Nav/NavMain.js
  src/components/Nav/NavSub.js
  src/components/Nav/NavSub.scss
  src/components/TitleLine/TitleLine.js
  src/pages/Main/components/NewestProduct.js
  src/pages/Main/components/ProductLineup.js
  src/pages/Main/components/ProductLineup.scss
  src/pages/Main/components/StarFullIcon.js
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/pages/ProductList/components/ProdcutListCont.js
  src/pages/ProductList/components/ProductListCont.scss
  src/pages/ProductList/components/ProductListNav.js
  src/styles/common.scss
Labels: 멘토 리뷰 요청

#29 Add : 헤더 푸터 연결, scss풀리는 현상 해결
  src/Router.js
  src/components/CategoryModal/CategoryModal.js
  src/components/CategoryModal/CategoryModalNav.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Header/Header.js
  src/pages/Details/Mainlayout.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/components/NewestNav.scss
  src/pages/Main/components/NewestPrdouct.scss
Labels: 멘토 리뷰 요청

#30 [45기 오승민] Add : 장바구니페이지 기능 구현 완료
  public/data/cartData.json
  public/data/data2.json
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/Components/Blank.js
  src/pages/Cart/Components/BuyingButton.js
  src/pages/Cart/Components/Count.js
  src/pages/Cart/Components/Count.scss
  src/pages/Cart/Components/LeftSide.js
  src/pages/Cart/Components/LeftSide.scss
  src/pages/Cart/Components/List.js
  src/pages/Cart/Components/List.scss
  src/pages/Cart/Components/ListItem.js
  src/pages/Cart/Components/ListItem.scss
  src/pages/Cart/Components/OrderInfo.js
  src/pages/Cart/Components/Product.js
  src/pages/Cart/Components/Product.scss
  src/pages/Cart/Components/ProductItem.js
  src/pages/Cart/Components/ProductItem.scss
  src/pages/Cart/Components/RightSide.js
  src/pages/Cart/Components/RightSide.scss
  src/pages/Cart/Components/ShippingFree.js
  src/pages/Cart/Components/ShippingFree.scss
  src/pages/Cart/Components/Summary.js
  src/pages/Cart/Components/Summary.scss
  src/pages/Cart/Components/Title.js
  src/pages/Cart/Components/Title.scss
Labels: 추가 기능 구현 중

#31 [45기 김희연] 상품디테일 페이지 품절 표시 추가
  src/pages/Details/components/Button.scss
  src/pages/Details/components/Contents.js
  src/pages/Details/components/SubscribeOptions.js
Labels: 멘토 리뷰 요청

#35 [45기 김희연] 상품디테일 레이아웃 일부 수정, 장바구니 버튼 로직 수정
  src/pages/Details/Details.js
  src/pages/Details/Details.scss
  src/pages/Details/components/Contents.js
Labels: 멘토 리뷰 요청

#36 [45기 오승민] Modify : 장바구니 페이지 기능 수정
  src/pages/Cart/Cart.js
  src/pages/Cart/Components/LeftSide.js
  src/pages/Cart/Components/ProductItem.js
Labels: 멘토 리뷰 요청

#37 [45기 이소진] Modify : 체크박스 필수 사항 체크 안할 시 알림창 설정
  src/pages/Login/Login.js
  src/pages/Signup/Signup.js
Labels: 멘토 리뷰 요청

#39 [45기 이소진] Modify : 로그인 페이지 수정
  src/pages/Login/Login.js
Labels: 멘토 리뷰 요청

#40 [45기 이소진] Modify : Debug1
  src/components/Nav/NavMain.js
  src/components/TitleLine/TitleLine.js
  src/pages/Cart/Cart.js
  src/pages/Cart/Components/Blank.js
  src/pages/Cart/Components/LeftSide.js
  src/pages/Cart/Components/RightSide.scss
  src/pages/Details/components/Button.scss
  src/pages/Details/components/Review.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Main/components/ProductLineup.js
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
Labels: 멘토 리뷰 요청

#24 [45기 박현아] Add: 결제페이지 통신구현
  public/data/orderItemsData.json
  src/Router.js
  src/components/TitleLine/TitleLine.js
  src/pages/Cart/Cart.js
  src/pages/Cart/Components/LeftSide.js
  src/pages/Details/components/Contents.js
  src/pages/Mypage/Mypage.js
  src/pages/Mypage/components/Likes.js
  src/pages/Mypage/components/LikesList.js
  src/pages/Mypage/components/LikesProduct.js
  src/pages/Mypage/components/MenuBar.js
  src/pages/Mypage/components/MypageTop.js
  src/pages/Payment/OrderCompleted.js
  src/pages/Payment/Payment.js
  src/pages/Payment/components/Agreement.js
  src/pages/Payment/components/Agreement.scss
  src/pages/Payment/components/OrderList.js
  src/pages/Payment/components/PaymentMethod.js
  src/pages/Payment/components/Shipment.js
  src/pages/ProductList/components/ProdcutListCont.js
Labels: 완료
